import 'package:flutter/material.dart';
import 'home_screen.dart';

class PrivacyPolicyScreen extends StatefulWidget {
  const PrivacyPolicyScreen({super.key});

  @override
  State<PrivacyPolicyScreen> createState() => _PrivacyPolicyScreenState();
}

class _PrivacyPolicyScreenState extends State<PrivacyPolicyScreen> {
  @override
  Widget build(BuildContext context) {
    final screenWidth = MediaQuery.of(context).size.width;
    final isSmallScreen = screenWidth < 600;

    return Scaffold(
      appBar: AppBar(

        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios, color: Colors.white),
          onPressed: () {
            Navigator.pushReplacement(
              context,
              MaterialPageRoute(builder: (context) => const HomeScreen()),
            );
          },
        ),
        backgroundColor: Colors.deepOrangeAccent,
        title:  Text(
            'Privacy Policy',
            style: TextStyle(color: Colors.white),

        ),
        centerTitle: true,

      ),
      backgroundColor: const Color(0xFFF6F8FC),
      body: SingleChildScrollView(
        padding: EdgeInsets.symmetric(horizontal: isSmallScreen ? 16.0 : 32.0),
    child: Column(
    crossAxisAlignment: CrossAxisAlignment.start,
    children: [
    const SizedBox(height: 16),
    // Page Title
    Text(
    'Privacy Policy for Tip Cal App',
    style: TextStyle(
    fontSize: isSmallScreen ? 20 : 24,
    fontWeight: FontWeight.bold,
    color: Colors.black,
    ),
    ),
    const SizedBox(height: 8),
    // Last Updated
    Text(
    'Last Updated: January 2024',
    style: TextStyle(
    fontSize: isSmallScreen ? 14 : 16,
    color: Colors.grey,
    ),
    ),
    const SizedBox(height: 16),
    // Sections
    _buildSectionTitle('Introduction'),
    _buildSectionContent(
    'Welcome to the Tip Calculator app. We value your privacy and are committed to protecting your personal information. This Privacy Policy outlines how we collect, use, and safeguard your data when you use our app.',
    ),
    _buildSectionTitle('Information We Collect'),
    _buildSectionContent(
    'We do not collect any personally identifiable information (PII) such as your name, email address, or phone number. The app operates locally on your device and does not require you to input any personal data.',
    ),
    _buildSectionTitle('Use of Information'),
    _buildSectionContent(
    'Since we do not collect personal information, the data generated by your use of the app (e.g., tip calculations, bill amounts) remains entirely on your device. We do not store or share this data with third parties.',
    ),
    _buildSectionTitle('Third-Party Services'),
    _buildSectionContent(
    'Our app does not use any third-party services that collect or process user data. Your interactions with the app are private and not shared with any external entities.',
    ),
    _buildSectionTitle('Children\'s Privacy'),
    _buildSectionContent(
    'The Tip Calculator app is not directed toward               knowingly collect personal information from children. If we become aware that we have inadvertently collected such information, we will take immediate steps to delete it.',
    ),
      _buildSectionTitle('Changes to the Privacy Policy'),
      _buildSectionContent(
        'We may update our Privacy Policy from time to time. Any changes will be reflected by updating the "Effective Date" at the top of this policy. We encourage you to review this policy periodically to stay informed about how we are protecting your information.',
      ),
      const SizedBox(height: 24),
    ],
    ),
      ),
    );
  }

  Widget _buildSectionTitle(String title) {
    return Padding(
      padding: const EdgeInsets.only(top: 16.0),
      child: Text(
        title,
        style: const TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.bold,
          color: Colors.black,
        ),
      ),
    );
  }

  Widget _buildSectionContent(String content) {
    return Padding(
      padding: const EdgeInsets.only(top: 8.0),
      child: Text(
        content,
        style: const TextStyle(
          fontSize: 14,
          color: Colors.black54,
          height: 1.5, // For better readability
        ),
      ),
    );
  }
}
